### ISSUE TITLE
Update meteor to the latest version

### ISSUE THREAD

**Issue by inderpreetsingh** [BRL-CAD/OGV-meteor#54]
Currently, we are using an old-ish version of meteor. We would like to move it to the latest version (1.6.1).

**Comment by Max2020q** [comment]
I will look into the release notes for the newer Meteor versions and see if anythings conflicting with updating.

About to submit a PR of upgrading this to 1.6.1 and Three.js to R103!

Cheers!

**Comment by Max2020q** [comment]
I actually ended up updating to the latest version of Meteor.js 1.8.1 

Most likely due to issues restarting the MongoDB server, I had connection and dependency errors when upgrading to 1.6.1 which caused me to have to patch to 1.6.1.2 and eventually update to 1.8.1.

Meteor 1.8.1 seems to be working nicely, however I will continue to test updates to see if anything pops up in the web developer console regarding package conflicts or Meteor.js .

**Comment by Max2020q** [comment]
I have solved this through updating Meteor to 1.8.1 in https://github.com/BRL-CAD/OGV-meteor/pull/88

**Comment by Max2020q** [comment]
Would like to close now that this is merged https://github.com/BRL-CAD/OGV-meteor/pull/88
